### ISSUE TITLE
lisk-forging-enable.sh - optimization for automation

### ISSUE THREAD

**Issue by punkrock** [Gr33nDrag0n69/LiskCore3Tools#5]
regarding your enable forging script that now check if the node is in sync. i think it would be better that if sync = true, it just waits instead of aborting and checks every minute if sync = false and as soon it is false it executes the remaining script and enables forging. at least for those who enter the encryption passphrase for automatisation.

**Comment by Gr33nDrag0n69** [comment]
sync can be true, false & undefined (lisk-core not running or running for less then a couple seconds)

**Comment by Gr33nDrag0n69** [comment]
i think if undefined it should still close with a warning

**Comment by Gr33nDrag0n69** [comment]
i don't think i will make the feature only when the script is run with passphrase

**Comment by Gr33nDrag0n69** [comment]
I worked a lot on the script. It's almost ready to be merged in main branch.
It still need some testing but here is current dev version
https://github.com/Gr33nDrag0n69/LiskCore3Tools/blob/lisk-forging-enable.sh_v1.3.0/SH/lisk-forging-enable.sh

**Comment by Gr33nDrag0n69** [comment]
1 :21 am here, I tough I would finish tonight but it will need another couple hours to test it "production ready"

**Comment by Gr33nDrag0n69** [comment]
https://github.com/Gr33nDrag0n69/LiskCore3Tools/pull/9
